import { BaseInterface } from "./base-interface";
import { CandidateStages } from "./candidateStages";
import { Designation } from "./designation";
import { JobDescription } from "./job-description";
import { User } from "./user";


export interface Candidate extends BaseInterface {
  first_name: string,
  last_name: string,
  date_of_birth: string,
  primary_email: string,
  secondary_email: string,
  primary_phone_number: string,
  secondary_phone_number: string,
  company_name: string,
  skills_1: string,
  skills_2: string,
  //salary: number,
  min_salary: number,
  max_salary: number,
  min_rate: number,
  max_rate: number,
  // rate:number,
  qualification: string,
  additional_qualification: string,
  certification: string,
  visa: string,
  current_location: string,
  total_experience: number,
  reason_for_job_change: string,
  rtr_done: string,
  willing_to_work_on_our_w2: string,
  open_for_relocation: string,
  rank: number,
  total_experience_in_usa: number,
  any_offer_in_hand: string,
  certification_doc: any,
  additional_qualification_doc: any,
  resume: any,
  remarks: string,
  resume_raw_data: string,
  submission_date: string,
  stage: any,
  stage_name: any,
  recruiter_name: string,
  designation: Designation,
  //  job_description: JobDescription | string,
  job_description: any,
  jd_name: any,
  job_descriptions: any,
  id?: string,
  created_at?: string,
  updated_at?: string,
  created_by?: User,
  updated_by?: User,
  isSalary?: string
  notes?: string,
  send_out_date?: string,
  employer_phone_number?: string,
  employer_name?: string,
  employer_email?: string,
  driving_license: any,
  offer_letter: any,
  passport: any,
  country: any,
  rtr: any,
  salary_slip: any,
  visa_copy: any,
  i94_document: any,
  educational_document: any,
  engagement_type: string,
  currency: string
}

export interface JobDescriptions {
  status: string,
  stage_name: string,
  job: string,
  jd_name: string,
  display_date: string,
  submission_date: string,
  notes: string,
  stage: any,
  send_out_date: string
}