// below are view permissions only
export enum PredefinedPermissions {
    GROUP = 'view_group',
    PERMISSION = 'view_permission',
    ACTIVITY_STATUS_MODEL = 'view_activitystatusmodel',
    CANDIDATES = 'view_candidates',
    CANDDIATE_SUBMISSION = 'view_candidatessubmissionmodel',
    CANDIDATE_STAGE = 'view_candidatestagemodel',
    CANDIDATE_EMAIL_TEMPLATE = 'view_emailtemplatemodel',
    CANDIDATE_MAIL = 'view_mailmodel',
    CANDIDATE_PLACEMENT_CARD = 'view_placementcardmodel',
    RTR_MAIL = 'view_rtrmailmodel',
    RTR = 'view_rtrmodel',
    SEARCH_TEARM = 'view_searchtermmodel',
    CANDIDATE_REPOSITORY = 'view_candidatesrepositerymodel',
    CLIENT = 'view_clientmodel',
    INTERVIEWER = 'view_interviewersmodel',
    TIMESLOT = 'view_timeslotsmodel',
    FEEDBACK = 'view_feedbackmodel',
    INTERVIEWS = 'view_interviewsmodel',
    JOB_ASSIGNMENT = 'view_jobassingmentmodel',
    JOB = 'view_jobmodel',
    JOB_SUBMISSION = 'view_jobsubmissionmodel',
    USER = 'view_user',
    VENDOR_EMAIL_TEMPLATE = 'view_vendoremailtemplatemodel',
    VENDOR_LIST = 'view_vendorlistmodel',
    CAMPAIGN_LIST = 'view_campaignlistdatamodel',
    VENDOR_MAIL = 'view_vendormailmodel',
    VENDOR = 'view_vendormodel',
    CAMPAIGN = 'view_campaignlistuploaddatamodel',
}